/**
 * CPython's `random.Random`, reimplemented — MT19937 with CPython's own
 * integer seeding, `random()` and `uniform()`.
 *
 * WHY THIS EXISTS, rather than `Math.random()` or any small PRNG:
 *
 * Rule 12 (humanization) decides every event's exact performed time and
 * velocity by drawing from `random.Random(...)`, and Rule 26 promises
 * that the same seed reproduces an identical performance. Those two
 * facts together mean the generator is not an implementation detail that
 * a port may swap out -- it is part of the engine's observable contract.
 * A different RNG here would produce a performance that is *plausible*
 * and *not the one the Python produces*, which would make the parity
 * tests meaningless and silently break the documented guarantee.
 *
 * Every line below mirrors CPython's `Modules/_randommodule.c` and
 * `Lib/random.py`. `test/unit/mt19937.test.js` checks it against values
 * generated by a real Python interpreter, so a mistake here fails a test
 * rather than quietly shifting every note by a few milliseconds.
 */

const N = 624;
const M = 397;
const MATRIX_A = 0x9908b0df;
const UPPER_MASK = 0x80000000;
const LOWER_MASK = 0x7fffffff;

export class PythonRandom {
  private readonly mt = new Uint32Array(N);
  private index = N + 1;

  /**
   * `random.Random(seed)` for a non-negative integer seed.
   *
   * Takes a bigint because the engine's own seeds are the top 64 bits of
   * a SHA-256 digest, which is far past `Number.MAX_SAFE_INTEGER` -- a
   * number would silently lose the low bits and every draw would differ.
   */
  constructor(seed: bigint) {
    // CPython: `n = abs(arg)`, then split into 32-bit chunks from the
    // right, then init_by_array. `bits == 0 ? 1 : (bits - 1) / 32 + 1`.
    let n = seed < 0n ? -seed : seed;
    const bits = bitLength(n);
    const keyUsed = bits === 0 ? 1 : Math.floor((bits - 1) / 32) + 1;
    const key = new Uint32Array(keyUsed);
    for (let i = 0; i < keyUsed; i++) {
      key[i] = Number(n & 0xffffffffn) >>> 0;
      n >>= 32n;
    }
    this.initByArray(key);
  }

  private initGenrand(s: number): void {
    this.mt[0] = s >>> 0;
    for (let i = 1; i < N; i++) {
      const prev = this.mt[i - 1] as number;
      this.mt[i] = (Math.imul(1812433253, prev ^ (prev >>> 30)) + i) >>> 0;
    }
    this.index = N;
  }

  private initByArray(key: Uint32Array): void {
    this.initGenrand(19650218);
    let i = 1;
    let j = 0;
    let k = Math.max(N, key.length);
    for (; k > 0; k--) {
      const prev = this.mt[i - 1] as number;
      this.mt[i] =
        ((((this.mt[i] as number) ^ Math.imul(prev ^ (prev >>> 30), 1664525)) >>> 0) +
          (key[j] as number) +
          j) >>>
        0;
      i++;
      j++;
      if (i >= N) {
        this.mt[0] = this.mt[N - 1] as number;
        i = 1;
      }
      if (j >= key.length) j = 0;
    }
    for (k = N - 1; k > 0; k--) {
      const prev = this.mt[i - 1] as number;
      this.mt[i] =
        ((((this.mt[i] as number) ^ Math.imul(prev ^ (prev >>> 30), 1566083941)) >>> 0) - i) >>> 0;
      i++;
      if (i >= N) {
        this.mt[0] = this.mt[N - 1] as number;
        i = 1;
      }
    }
    this.mt[0] = UPPER_MASK;
  }

  /** `genrand_uint32` — the twist, then the tempering. */
  genrandUint32(): number {
    if (this.index >= N) {
      for (let kk = 0; kk < N - M; kk++) {
        const y =
          (((this.mt[kk] as number) & UPPER_MASK) | ((this.mt[kk + 1] as number) & LOWER_MASK)) >>>
          0;
        this.mt[kk] = ((this.mt[kk + M] as number) ^ (y >>> 1) ^ (y & 1 ? MATRIX_A : 0)) >>> 0;
      }
      for (let kk = N - M; kk < N - 1; kk++) {
        const y =
          (((this.mt[kk] as number) & UPPER_MASK) | ((this.mt[kk + 1] as number) & LOWER_MASK)) >>>
          0;
        this.mt[kk] =
          ((this.mt[kk + (M - N)] as number) ^ (y >>> 1) ^ (y & 1 ? MATRIX_A : 0)) >>> 0;
      }
      const y =
        (((this.mt[N - 1] as number) & UPPER_MASK) | ((this.mt[0] as number) & LOWER_MASK)) >>> 0;
      this.mt[N - 1] = ((this.mt[M - 1] as number) ^ (y >>> 1) ^ (y & 1 ? MATRIX_A : 0)) >>> 0;
      this.index = 0;
    }

    let y = this.mt[this.index++] as number;
    y ^= y >>> 11;
    y = (y ^ ((y << 7) & 0x9d2c5680)) >>> 0;
    y = (y ^ ((y << 15) & 0xefc60000)) >>> 0;
    y ^= y >>> 18;
    return y >>> 0;
  }

  /**
   * `random.random()`: 53 bits of randomness assembled from two 32-bit
   * draws, exactly as CPython does it -- `(a * 67108864.0 + b) / 2**53`
   * where a is 27 bits and b is 26.
   */
  random(): number {
    const a = this.genrandUint32() >>> 5;
    const b = this.genrandUint32() >>> 6;
    return (a * 67108864.0 + b) * (1.0 / 9007199254740992.0);
  }

  /** `random.uniform(a, b)` — CPython's literal `a + (b - a) * random()`. */
  uniform(a: number, b: number): number {
    return a + (b - a) * this.random();
  }

  /** `random.getrandbits(k)` for k <= 32, which is all this engine asks for. */
  getRandBits(k: number): number {
    if (k <= 0) return 0;
    if (k > 32) throw new Error('getRandBits is implemented for k <= 32 only');
    return this.genrandUint32() >>> (32 - k);
  }

  /** `random._randbelow`: rejection sampling on `getrandbits(bit_length(n))`. */
  randBelow(n: number): number {
    if (n <= 0) return 0;
    const k = 32 - Math.clz32(n);
    let r = this.getRandBits(k);
    while (r >= n) r = this.getRandBits(k);
    return r;
  }

  /** `random.choice(seq)`. */
  choice<T>(seq: readonly T[]): T {
    return seq[this.randBelow(seq.length)] as T;
  }
}

/** `int.bit_length()` for a non-negative bigint. */
function bitLength(n: bigint): number {
  if (n === 0n) return 0;
  return n.toString(2).length;
}
